# Generated by Django 5.2.5 on 2025-08-25 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('prod', 'Production')], default='sandbox', max_length=16)),
                ('api_key_encrypted', models.TextField()),
                ('tester_msisdn', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_integrations', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=3)),
                ('wa_id', models.CharField(max_length=32)),
                ('msg_id', models.CharField(blank=True, default='', max_length=100)),
                ('msg_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=24)),
                ('text', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wa360.waintegration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='waintegration',
            index=models.Index(fields=['organization', 'mode'], name='wa360_waint_organiz_6e6c56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waintegration',
            unique_together={('organization', 'mode')},
        ),
        migrations.AddIndex(
            model_name='wamessage',
            index=models.Index(fields=['integration', 'created_at'], name='wa360_wames_integra_107633_idx'),
        ),
    ]
