# Generated by Django 5.2.5 on 2025-08-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waintegration',
            name='raw_api_key',
            field=models.CharField(blank=True, help_text='Raw API key (will be encrypted automatically)', max_length=200),
        ),
        migrations.AlterField(
            model_name='waintegration',
            name='api_key_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted API key (auto-generated)'),
        ),
    ]
