# Generated by Django 5.2.5 on 2025-08-27 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa360', '0002_waintegration_raw_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wamessage',
            name='msg_id',
            field=models.CharField(blank=True, default='', help_text='Unique message ID from WhatsApp', max_length=100),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('template', 'Template')], default='text', max_length=24),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Full message payload from WhatsApp'),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='text',
            field=models.TextField(blank=True, default='', help_text='Message text content'),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='wa_id',
            field=models.CharField(help_text='WhatsApp ID of sender/recipient', max_length=32),
        ),
        migrations.CreateModel(
            name='WaConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(db_index=True, help_text='WhatsApp ID of the contact', max_length=32)),
                ('started_by', models.CharField(blank=True, default='admin', help_text='Who started the conversation: admin|contact|system', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_msg_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='wa360.waintegration')),
            ],
            options={
                'ordering': ['-last_msg_at'],
            },
        ),
        migrations.AddField(
            model_name='wamessage',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Conversation this message belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='wa360.waconversation'),
        ),
        migrations.AddIndex(
            model_name='wamessage',
            index=models.Index(fields=['conversation', 'created_at'], name='wa360_wames_convers_00f565_idx'),
        ),
        migrations.AddConstraint(
            model_name='wamessage',
            constraint=models.UniqueConstraint(fields=('integration', 'msg_id'), name='uniq_integration_msgid'),
        ),
        migrations.AddIndex(
            model_name='waconversation',
            index=models.Index(fields=['integration', 'wa_id'], name='wa360_wacon_integra_105bae_idx'),
        ),
        migrations.AddIndex(
            model_name='waconversation',
            index=models.Index(fields=['status', 'last_msg_at'], name='wa360_wacon_status_7e96bf_idx'),
        ),
    ]
