# Generated by Django 5.2.5 on 2025-09-09 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('wa360', '0003_alter_wamessage_msg_id_alter_wamessage_msg_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='AI-generated conversation summary')),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages when summary was generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_api_key', models.CharField(blank=True, help_text='OpenAI API key (will be encrypted)', max_length=200)),
                ('api_key_encrypted', models.TextField(blank=True, help_text='Encrypted API key')),
                ('model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4.1', 'GPT-4.1')], default='gpt-4o-mini', max_length=20)),
                ('temperature', models.FloatField(default=0.7, help_text='0.0 to 1.0')),
                ('max_tokens', models.IntegerField(default=1000, help_text='Maximum response tokens')),
                ('client_context', models.TextField(blank=True, help_text='Client details and context')),
                ('project_context', models.TextField(blank=True, help_text='Project details and context')),
                ('custom_instructions', models.TextField(blank=True, help_text='Custom behavior instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='wamessage',
            name='uniq_integration_msgid',
        ),
        migrations.RemoveIndex(
            model_name='wamessage',
            name='wa360_wames_integra_107633_idx',
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wa360.waconversation'),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='direction',
            field=models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=8),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='msg_id',
            field=models.CharField(blank=True, help_text='WhatsApp message ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('location', 'Location'), ('contact', 'Contact'), ('sticker', 'Sticker'), ('template', 'Template')], default='text', max_length=16),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='payload',
            field=models.JSONField(default=dict, help_text='Full message payload from WhatsApp'),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='text',
            field=models.TextField(blank=True, help_text='Message text content'),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='wa_id',
            field=models.CharField(db_index=True, help_text='WhatsApp ID of the contact', max_length=32),
        ),
        migrations.AddIndex(
            model_name='wamessage',
            index=models.Index(fields=['integration', 'wa_id'], name='wa360_wames_integra_9582b9_idx'),
        ),
        migrations.AddIndex(
            model_name='wamessage',
            index=models.Index(fields=['direction', 'created_at'], name='wa360_wames_directi_50f960_idx'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='wa360.waconversation'),
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_config', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='conversationsummary',
            index=models.Index(fields=['conversation', 'updated_at'], name='wa360_conve_convers_ab0a51_idx'),
        ),
        migrations.AddIndex(
            model_name='llmconfiguration',
            index=models.Index(fields=['organization'], name='wa360_llmco_organiz_e42bd0_idx'),
        ),
    ]
