# Generated by Django 5.2.5 on 2025-09-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa360', '0004_conversationsummary_llmconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wamessage',
            name='msg_id',
            field=models.CharField(blank=True, help_text='WhatsApp message ID', max_length=128),
        ),
    ]
