# Generated by Django 5.2.6 on 2025-09-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('wa360', '0005_alter_wamessage_msg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicMessageSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('minute', 'Every Minute (Testing)'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('disabled', 'Disabled')], default='daily', help_text='How often to send periodic messages', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable periodic messaging')),
                ('last_sent', models.DateTimeField(blank=True, help_text='When the last periodic message was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_schedule', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Periodic Message Schedule',
                'verbose_name_plural': 'Periodic Message Schedules',
                'ordering': ['-updated_at'],
            },
        ),
    ]
