# Generated by Django 5.2.6 on 2025-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa360', '0006_periodicmessageschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waconversation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('continue', 'Continue - Client Engaged'), ('schedule_later', 'Schedule Later - Client Postponed'), ('evaluating', 'Evaluating - AI Analysis in Progress')], default='open', max_length=60),
        ),
    ]
