# Generated by Django 5.2.6 on 2025-10-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wa360', '0007_alter_waconversation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waintegration',
            unique_together=set(),
        ),
    ]
