# Generated by Django 5.2.6 on 2025-10-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa360', '0008_alter_waintegration_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmconfiguration',
            name='client_context',
        ),
        migrations.RemoveField(
            model_name='llmconfiguration',
            name='custom_instructions',
        ),
        migrations.RemoveField(
            model_name='llmconfiguration',
            name='project_context',
        ),
        migrations.AddField(
            model_name='waintegration',
            name='client_context',
            field=models.TextField(blank=True, help_text='Client details and context for this WhatsApp number'),
        ),
        migrations.AddField(
            model_name='waintegration',
            name='custom_instructions',
            field=models.TextField(blank=True, help_text='Custom behavior instructions for this WhatsApp number'),
        ),
        migrations.AddField(
            model_name='waintegration',
            name='project_context',
            field=models.TextField(blank=True, help_text='Project details and context for this WhatsApp number'),
        ),
    ]
